JobAd\Domain\Model\JobAdvertisement\Events\CityWasAddedToJobAdvertisement:
    exclusion_policy: all
    
    properties:
        id:
            type: string
        city:
            type: string
        postCode:
            type: int
        occurredOn:
            expose: true
            type: CustomDateTimeImmutable