JobAd\Domain\Model\JobAdvertisement\Events\CategoryWasRemoveFromJobAd:
    exclusion_policy: all
    
    properties:
        id:
            type: string
        categoryId:
            type: string
        occurredOn:
            expose: true
            type: CustomDateTimeImmutable