JobAd\Domain\Model\JobAdvertisement\Events\CategoryWasAddToJobAd:
    exclusion_policy: all
    
    properties:
        id:
            type: string
        categoryId:
            type: string
        name:
            type: string
        occurredOn:
            expose: true
            type: CustomDateTimeImmutable
