JobAd\Domain\Model\JobAdvertisement\Events\TagWasAddedToJobAd:
    exclusion_policy: all
    
    properties:
        id:
            type: string
        tagId:
            type: string
        name:
            type: string
        occurredOn:
            expose: true
            type: CustomDateTimeImmutable
