JobAd\Domain\Model\JobAdvertisement\Events\JobAdWasDrafted:
    exclusion_policy: all
    
    properties:
        id:
            type: JobAd\Domain\Model\JobAdvertisement\Id
        pozitonTitle:
            type: JobAd\Domain\Model\JobAdvertisement\PozitonTitle
        description:
            type: JobAd\Domain\Model\JobAdvertisement\Description
        howToApplay:
            type: JobAd\Domain\Model\JobAdvertisement\HowToApplay
        occurredOn:
            expose: true
            type: CustomDateTimeImmutable